#%RAML 1.0
title: airindiaapi
baseUri: http://localhost:8081/api

/airIndiaFlights:
  get:
    queryParameters:
      source:
        example: DEL
      destination:
        example: MUM
      doj:
        example: 31-May-2021
    responses:
      200:
        body:
          application/json:
            example: 
                      [
                        {
                            "Id": "201",
                            "airlineName": "AirIndia",
                            "fCode": "AI201",
                            "fromAirportCode": "DEL",
                            "toAirportCode": "MUM",
                            "departureDate": "31-May-2021",
                            "emptySeats": "0",
                            "totalSeats": 200,
                            "price": "199",
                            "planeType": "AirIndia 737"
                        },
                        {
                            "Id": "202",
                            "airlineName": "AirIndia",
                            "fCode": "AI202",
                            "fromAirportCode": "DEL",
                            "toAirportCode": "MUM",
                            "departureDate": "31-May-2021",
                            "emptySeats": "24",
                            "totalSeats": 350,
                            "price": "450",
                            "planeType": "AirIndia 747"
                        },
                        {
                            "Id": "203",
                            "airlineName": "AirIndia",
                            "fCode": "AI203",
                            "fromAirportCode": "DEL",
                            "toAirportCode": "MUM",
                            "departureDate": "31-May-2021",
                            "emptySeats": "33",
                            "totalSeats": 400,
                            "price": "450",
                            "planeType": "AirIndia 757"
                        }
                    ]